version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./unifydata:/var/www/unifydata
      - ./nginx/unifydata.conf:/etc/nginx/sites-available/unifydata.conf
      - ./laravel-cron:/etc/cron.d/laravel-cron

    ports:
      - "8081:80"
    depends_on:
      - postgresql
      - mongo

  postgresql:
    image: postgres:15
    container_name: postgresql
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  dbdata:
    driver: local
  mongodb_data:
    driver: local
